apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - https://github.com/codefresh-io/argo-workflows/releases/download/v3.4.4-cf/install.yaml
images:
- name: quay.io/codefresh/argocli
  newName: kimaharfi/argocli
  newTag: CR-15902-test-3

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argo-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --auth-mode=server
  - target:
      version: v1
      kind: ConfigMap
      name: workflow-controller-configmap
    patch: |-
      - op: add
        path: /data
        value:
          workflowDefaults: |
            spec:
              ttlStrategy:
                secondsAfterCompletion: 86400
                secondsAfterSuccess: 86400
                secondsAfterFailure: 86400
              podGC:
                strategy: OnWorkflowCompletion
                labelSelector:
                  matchLabels:
                    should-be-deleted: "true"
