apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - https://github.com/codefresh-io/argo-workflows/releases/download/v3.4.0-cf/install.yaml
# - https://github.com/codefresh-io/argo-workflows/manifests/base?ref=release-3.4
# - https://github.com/codefresh-io/argo-workflows/manifests/cluster-install/workflow-controller-rbac?ref=release-3.4
# - https://github.com/codefresh-io/argo-workflows/manifests/cluster-install/argo-server-rbac?ref=release-3.4

patches:
  # reset the crbs to `subject.namespace: default`, so that argo-cd will later change them to the actual ns
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: argo

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argo-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --auth-mode=server

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: workflow-controller
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args/3
        value: quay.io/codefresh/argoexec:v3.4.0-cf

  - target:
      version: v1
      kind: ConfigMap
      name: workflow-controller-configmap
    patch: |-
      - op: add
        path: /data
        value:
          workflowDefaults: |
            spec:
              ttlStrategy:
                secondsAfterCompletion: 86400
                secondsAfterSuccess: 86400
                secondsAfterFailure: 86400
              podGC:
                strategy: OnWorkflowCompletion
                labelSelector:
                  matchLabels:
                    should-be-deleted: "true"

images:
- name: quay.io/codefresh/argocli
  newName: quay.io/codefresh/argocli
  newTag: v3.4.0-cf
- name: quay.io/codefresh/workflow-controller
  newName: quay.io/codefresh/workflow-controller
  newTag: v3.4.0-cf