apiVersion: codefresh.io/v1alpha1
kind: Runtime
metadata:
  name: "{{ name }}"
  namespace: "{{ namespace }}"
spec:
  requiredCLIVersion: ^0.1.0-0
  version: 0.1.14
  bootstrapSpecifier: github.com/codefresh-io/csdp-official.git/csdp/hybrid/basic/apps/argo-cd?ref=quay-registry
  components:
    - name: events
      type: kustomize
      url: github.com/codefresh-io/csdp-official/csdp/hybrid/basic/apps/argo-events?ref=quay-registry
      wait: true
    - name: rollouts
      type: kustomize
      url: github.com/codefresh-io/csdp-official/csdp/hybrid/basic/apps/argo-rollouts?ref=quay-registry
    - name: app-proxy
      type: kustomize
      url: github.com/codefresh-io/csdp-official/csdp/hybrid/basic/apps/app-proxy?ref=quay-registry
      syncWave: 9
    - name: internal-router
      type: kustomize
      url: github.com/codefresh-io/csdp-official/csdp/hybrid/basic/apps/internal-router?ref=quay-registry
      syncWave: 10
    - name: sealed-secrets
      type: kustomize
      url: github.com/codefresh-io/csdp-official/csdp/hybrid/basic/apps/sealed-secrets?ref=quay-registry
    - name: codefresh-tunnel-client
      type: helm
      url: github.com/codefresh-io/codefresh-tunnel-charts/codefresh-tunnel-client?ref=0.1.8
      feature: ingressless
