apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - pdb.yaml

patches:
  # Set 2 replicas for workflow controller
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: workflow-controller
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argo-server
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
