apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-manager-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-manager-role
subjects:
- kind: ServiceAccount
  name: argocd-manager
  namespace: kube-system
---
apiVersion: v1
data:
  annotations: |
    some.domain.com/key1: annotation_value1
    some.domain.com/key2: annotation_value2
  contextName: contextName_data
  ingressUrl: ingressUrl_data
  labels: |
    some.domain.com/key1: label_value1
    some.domain.com/key2: label_value2
  server: server_data
kind: ConfigMap
metadata:
  name: csdp-add-cluster-cm
  namespace: kube-system
---
apiVersion: v1
stringData:
  csdpToken: csdpToken_data
kind: Secret
metadata:
  name: csdp-add-cluster-secret
  namespace: kube-system
type: Opaque
---
apiVersion: batch/v1
kind: Job
metadata:
  name: csdp-add-cluster-job
  namespace: kube-system
spec:
  backoffLimit: 1
  template:
    metadata:
      name: csdp-add-cluster-pod
    spec:
      containers:
      - args:
        - '600'
        command:
        - sleep
        env:
        - name: SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: INGRESS_URL
          valueFrom:
            configMapKeyRef:
              key: ingressUrl
              name: csdp-add-cluster-cm
        - name: CSDP_TOKEN
          valueFrom:
            secretKeyRef:
              key: csdpToken
              name: csdp-add-cluster-secret
        - name: CONTEXT_NAME
          valueFrom:
            configMapKeyRef:
              key: contextName
              name: csdp-add-cluster-cm
        - name: SERVER
          valueFrom:
            configMapKeyRef:
              key: server
              name: csdp-add-cluster-cm
        - name: CSDP_TOKEN_SECRET
          value: csdp-add-cluster-secret
        image: quay.io/codefresh/csdp-add-cluster:0.4.0
        imagePullPolicy: Always
        name: main
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      restartPolicy: Never
      serviceAccount: argocd-manager
      volumes:
      - configMap:
          items:
          - key: annotations
            path: annotations.yaml
          - key: labels
            path: labels.yaml
          name: csdp-add-cluster-cm
        name: config-volume
  ttlSecondsAfterFinished: 600
