cf runtime uninstall codefresh-hosted-0 --silent --force &
cf runtime uninstall codefresh-hosted-1 --silent --force &
cf runtime uninstall codefresh-hosted-2 --silent --force &
cf runtime uninstall codefresh-hosted-3 --silent --force &
cf runtime uninstall codefresh-hosted-4 --silent --force &
cf runtime uninstall codefresh-hosted-5 --silent --force &
cf runtime uninstall codefresh-hosted-6 --silent --force &
cf runtime uninstall codefresh-hosted-7 --silent --force &
cf runtime uninstall codefresh-hosted-8 --silent --force &
cf runtime uninstall codefresh-hosted-9 --silent --force &
cf runtime uninstall codefresh-hosted-10 --silent --force &
cf runtime uninstall codefresh-hosted-11 --silent --force &
cf runtime uninstall codefresh-hosted-12 --silent --force &
cf runtime uninstall codefresh-hosted-13 --silent --force &
cf runtime uninstall codefresh-hosted-14 --silent --force &
cf runtime uninstall codefresh-hosted-15 --silent --force &
cf runtime uninstall codefresh-hosted-16 --silent --force &
cf runtime uninstall codefresh-hosted-17 --silent --force &
cf runtime uninstall codefresh-hosted-18 --silent --force &
