apiVersion: codefresh.io/v1alpha1
kind: Runtime
metadata:
  name: "{{ name }}"
  namespace: "{{ namespace }}"
spec:
  defVersion: 1.0.1
  version: 0.0.311
  bootstrapSpecifier: github.com/codefresh-io/cli-v2/manifests/argo-cd
  components:
    - name: argo-events
      type: kustomize
      url: github.com/codefresh-io/cli-v2/manifests/argo-events
      wait: true
    - name: app-proxy
      type: kustomize
      url: github.com/codefresh-io/cli-v2/manifests/app-proxy
