apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.5/controller.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: sealed-secrets-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --key-renew-period=720h
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/codefresh/sealed-secrets-controller:v0.17.5
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 32Mi
