apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-reporter-sa
roleRef:
  apiGroup: ""
  kind: Role
  name: rollout-reporter-sa
subjects:
  - kind: ServiceAccount
    name: rollout-reporter-sa
