apiVersion: v1
kind: Secret
metadata:
  name: csdp-installer
stringData:
  csdp.url: <CSDP_URL>
  csdp.token: <CSDP_TOKEN>
  runtime.name: <RUNTIME_NAME>
  runtime.repo: <RUNTIME_REPO>
  runtime.gitToken: <RUNTIME_GIT_TOKEN>
  runtime.cluster: <RUNTIME_CLUSTER>
  runtime.ingressURL: <RUNTIME_INGRESS_URL>
  runtime.ingressClass: <RUNTIME_INGRESS_CLASS>
  runtime.ingressController: <RUNTIME_INGRESS_CONTROLLER>
