apiVersion: batch/v1
kind: Job
metadata:
  name: csdp-installation-job
spec:
  ttlSecondsAfterFinished: 600 # stick around for 10m
  backoffLimit: 100
  template:
    metadata:
      labels:
        app: csdp-installer
      name: csdp-installation-job
    spec:
      serviceAccount: argocd-application-controller
      restartPolicy: Never
      containers:
        - name: csdp-installer
          image: quay.io/codefresh/csdp-installer
          imagePullPolicy: Always
          command:
            - bash
          args:
            - ./install.sh
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CSDP_URL
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: csdp.url
            - name: CSDP_RUNTIME_TOKEN
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: csdp.token
            - name: CSDP_RUNTIME_NAME
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: runtime.name
            - name: CSDP_RUNTIME_VERSION
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: runtime.version
                  optional: true
            - name: CSDP_RUNTIME_REPO
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: runtime.repo
            - name: CSDP_RUNTIME_GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: runtime.gitToken
            - name: CSDP_RUNTIME_CLUSTER
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: runtime.cluster
            - name: CSDP_RUNTIME_INGRESS_URL
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: runtime.ingressURL
            - name: CSDP_INGRESS_CLASS_NAME
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: runtime.ingressClass
            - name: CSDP_INGRESS_CONTROLLER
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: runtime.ingressController
            - name: CSDP_MANAGED_RUNTIME
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: runtime.managed
                  optional: true
            - name: CSDP_GIT_INTEGRATION_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: gitIntegration.provider
                  optional: true
            - name: CSDP_GIT_INTEGRATION_API_URL
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: gitIntegration.apiURL
                  optional: true
            - name: CSDP_GIT_INTEGRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: csdp-installer
                  key: gitIntegration.token
                  optional: true
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          securityContext:
            allowPrivilegeEscalation: false
