apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - pdb.yaml

components:
- ../components/ha-manifests
- ../components/codefresh-base

patches:
# ----------------HA------------------------------------------
# Set high availability for application controller
- target:
    group: apps
    version:  v1
    kind: StatefulSet
    name: argocd-application-controller
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ARGOCD_CONTROLLER_REPLICAS
        value: "2"
# Set requests for Redis
- target:
    name: argocd-redis-ha-server
    kind: StatefulSet
    group: apps
    version: v1
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 100m
          memory: 150Mi
- target:
    name: argocd-redis-ha-haproxy
    kind: StatefulSet
    group: apps
    version: v1
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 100m
          memory: 180Mi
# ------------------------------------------------------------