apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap-app-proxy
spec:
  template:
    replicas: 1
    spec:
      serviceAccountName: cap-app-proxy
      initContainers:
        - name: init-certs
          image: alpine:3.16
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - |
              /bin/sh <<'EOF'
              if [ "$(ls /app/config/tls)" ]; then
                echo "concatenating certs into /app/config/all/all.cer"
                cat /app/config/tls/* >> /app/config/all/all.cer
              else
                echo "no certs to concatenate"
              fi
              EOF
          volumeMounts:
            - mountPath: /app/config/tls
              name: tls-certs
              readOnly: true
            - mountPath: /app/config/all
              name: all-certs
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
            requests:
              memory: 256Mi
              cpu: '0.2'
      containers:
        - env:
            - name: ARGO_CD_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: argoCdInsecure
                  optional: true
            - name: ARGO_CD_URL
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: argoCdUrl
                  optional: true
            - name: ARGO_CD_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: argoCdUsername
                  optional: true
            - name: ARGO_CD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argocd-initial-admin-secret
                  key: password
            - name: ARGO_WORKFLOWS_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: argoWorkflowsInsecure
                  optional: true
            - name: ARGO_WORKFLOWS_URL
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: argoWorkflowsUrl
                  optional: true
            - name: CF_HOST
              valueFrom:
                configMapKeyRef:
                  name: codefresh-cm
                  key: base-url
                  optional: true
            - name: CORS
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: cors
                  optional: true
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: env
                  optional: true
            - name: ISC_ENSURED_EVENT_EMIT_DELAY
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: iscEnsuredEventEmitDelay
                  optional: true
            - name: IRW_CONCURRENCY_CM_KEY
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: irwConcurrencyCmKey
                  optional: true
            - name: IRW_CONCURRENCY_CM_NAME
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: irwConcurrentyCmName
                  optional: true
            - name: IRW_HEARTBEAT_INTERVAL_IN_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: irwHeartbeatIntervalInSeconds
                  optional: true
            - name: IRW_POD_GC_STRATEGY
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: irwPodGcStrategy
                  optional: true
            - name: IRW_SERVICE_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: irwServiceAccount
                  optional: true
            - name: IRW_TTL_ACTIVE_IN_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: irwTtlActiveInSeconds
                  optional: true
            - name: IRW_TTL_AFTER_COMPLETION_IN_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: irwTtlAfterCompletionInSeconds
                  optional: true
            - name: GRAPHQL_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: graphqlDebug
                  optional: true
            - name: GRAPHQL_PLAYGROUND
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: graphqlPlayground
                  optional: true
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: logLevel
                  optional: true
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: port
                  optional: true
            - name: GIT_INTEGRATION_APIURL
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: gitIntegrationApiUrl
                  optional: true
            - name: GIT_INTEGRATION_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: gitIntegrationProvider
                  optional: true
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: autopilot-secret
                  key: git_username
                  optional: true
            - name: GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: autopilot-secret
                  key: git_token
                  optional: true
            - name: NODE_EXTRA_CA_CERTS
              value: /app/config/all/all.cer
            - name: REPO_CREDS_SECRET_NAME
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: repoCredsSecretName
                  optional: true
            - name: REPO_LOCK_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: repoLockTimeout
                  optional: true
            - name: REPOS_DIR
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: reposDir
                  optional: true
            - name: RUNTIME_NAME
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: runtimeName
                  optional: true
            - name: RUNTIME_TOKEN
              valueFrom:
                secretKeyRef:
                  name: codefresh-token
                  key: token
            - name: RUNTIME_STORE_IV
              valueFrom:
                secretKeyRef:
                  name: codefresh-token
                  key: encryptionIV
                  optional: true
            - name: SEND_HEARTBEAT_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: sendHeartbeatInterval
                  optional: true
            - name: SKIP_PERMISSIONS_VALIDATION
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: skipPermissionsValidation
                  optional: true
            - name: STORE_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: storeBackend
                  optional: true
            - name: STRIP_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: stripPrefix
                  optional: true
            - name: USER_CACHE_TTL
              valueFrom:
                configMapKeyRef:
                  name: cap-app-proxy-cm
                  key: userCacheTtl
                  optional: true
            - name: USER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: codefresh-user-token
                  key: token
                  optional: true
          image: quay.io/codefresh/cap-app-proxy
          imagePullPolicy: Always
          name: cap-app-proxy
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 10
            httpGet:
              port: http
              path: /api/readyz
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
            httpGet:
              port: http
              path: /api/healthz
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: '512Mi'
              ephemeral-storage: '2Gi'
              cpu: '100m'
            limits:
              memory: '1Gi'
              ephemeral-storage: '6Gi'
              cpu: '1500m'
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /app/config/all
              name: all-certs
              readOnly: true
      volumes:
        - name: all-certs
          emptyDir: {}
        - name: tls-certs
          configMap:
            defaultMode: 420
            name: argocd-tls-certs-cm
