apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- app-proxy.deploy.yaml
- app-proxy.svc.yaml
- app-proxy.sa.yaml
- app-proxy.rb.yaml
- app-proxy.crb.yaml
- app-proxy.role.yaml
- app-proxy.cm.yaml

images:
- name: quay.io/codefresh/cap-app-proxy
  newName: quay.io/codefresh/cap-app-proxy
  newTag: 1.1982.0
- name: alpine
  newName: quay.io/codefresh/alpine
  newTag: '3.16'
