apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: quay.io/codefresh/cap-app-proxy
    newName: quay.io/codefresh/cap-app-proxy
    newTag: 1.1807.0
resources:
  - app-proxy.deploy.yaml
  - app-proxy.svc.yaml
  - app-proxy.sa.yaml
  - app-proxy.rb.yaml
  - app-proxy.crb.yaml
  - app-proxy.role.yaml
  - app-proxy.cm.yaml
  - ingress.yaml

patches:
  # This is a fix for ignoring invalid response header
  # from g.codefresh caused by imperva. Need to fix this
  # before removing this patch.
  - target:
      name: cap-app-proxy
      group: apps
      version: v1
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: NODE_ENV, value: '--insecure-http-parser' }
