apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
- name: quay.io/codefresh/cap-app-proxy
  newName: quay.io/codefresh/cap-app-proxy
  newTag: 1.2315.0-CR-19379-781c16c

resources:
- app-proxy.deploy.yaml
- app-proxy.svc.yaml
- app-proxy.sa.yaml
- app-proxy.rb.yaml
- app-proxy.crb.yaml
- app-proxy.role.yaml
- app-proxy.cm.yaml
