apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: quay.io/codefresh/cap-app-proxy
    newName: quay.io/codefresh/cap-app-proxy
    newTag: 1.1807.0
resources:
  - app-proxy.deploy.yaml
  - app-proxy.svc.yaml
  - app-proxy.sa.yaml
  - app-proxy.rb.yaml
  - app-proxy.crb.yaml
  - app-proxy.role.yaml
  - app-proxy.cm.yaml
  - ingress.yaml

pathches:
  - target:
    name: cap-app-proxy
    kind: Deployment
    group: apps
    version: v1
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: 512Mi
        limits:
          memory: 1Gi
