apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- pdb.yaml

commonLabels:
  app.kubernetes.io/part-of: cap-app-proxy

patches:
# increase replicas
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cap-app-proxy
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
# Add leader election sidecar
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cap-app-proxy
  path: leader-election.deployment.patch.yaml
# Add leader election role
- target:
    kind: Role
    name: cap-app-proxy
  patch: |-
    - op: add
      path: /rules/-
      value:
        apiGroups:
        - coordination.k8s.io
        resources:
        - leases
        verbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
    - op: add
      path: /rules/-
      value:
        apiGroups:
        - ""
        resources:
        - events
        verbs:
        - create
        - patch
