apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap-app-proxy
spec:
  template:
    spec:
      containers:
        - name: cap-app-proxy
          env:
            - name: LEADER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
        - name: leader-elector
          image: quay.io/roikramer120/leader-elector:v0.0.1
          command:
            - leader-elector
          args:
            - --id=$(POD_NAME)
            - --lease-name=$(LEASE_NAME)
            - --namespace=$(NAMESPACE)
            - --lease-duration=$(LEASE_DURATION)
            - --lease-renew-duration=$(LEASE_RENEW_DURATION)
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LEASE_NAME
              value: cap-app-proxy
            - name: LEASE_DURATION
              value: 10s
            - name: LEASE_RENEW_DURATION
              value: 5s
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4040
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 4040
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: IfNotPresent
