apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "csdp-add-cluster.fullname" . }}-cm
  namespace: kube-system
  labels:
    {{- include "csdp-add-cluster.labels" . | nindent 4 }}
data:
  ingressUrl: {{ .Values.ingressUrl | quote }}
  contextName: {{ .Values.contextName | quote }}
  server: {{ .Values.server | quote }}
  labels: {{ .Values.labels | base64 }}
  annotations: {{ .Values.annotations | base64 }}
