apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "csdp-add-cluster.fullname" . }}-cm
  namespace: kube-system
  labels:
    {{- include "csdp-add-cluster.labels" . | nindent 4 }}
data:
  ingressUrl: {{ required ".Values.ingressUrl is required!" .Values.ingressUrl | quote }}
  contextName: {{ required ".Values.contextName is required!" .Values.contextName | quote }}
  server: {{ required ".Values.server is required!" .Values.server | quote }}
  labels: {{ .Values.labels | quote }}
  annotations: {{ .Values.annotations | quote }}
