apiVersion: v1
kind: Secret
metadata:
  name: {{ include "csdp-add-cluster.fullname" . }}-secret
  namespace: {{ .Values.systemNamespace | default "kube-system" }}
  labels:
    {{- include "csdp-add-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  csdpToken: {{ .Values.csdpToken | b64enc | quote }}
