{{- if .Values.codefresh.userToken.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "csdp-add-cluster.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csdp-add-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  codefresh-api-token: {{ .Values.codefresh.userToken.token | b64enc | quote }}
{{- end }}
