{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csdp-add-cluster.serviceAccountName" . }}
  namespace: {{ .Values.systemNamespace | default "kube-system" }}
  labels:
    {{- include "csdp-add-cluster.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.secret }}
    {{- if .Values.serviceAccount.secret.create }}
secrets:
  - name: {{ include "csdp-add-cluster.serviceAccountName" . }}-sa-token
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "csdp-add-cluster.serviceAccountName" . }}-sa-token
  annotations:
    kubernetes.io/service-account.name: {{ include "csdp-add-cluster.serviceAccountName" . }}
    {{- end }}
  {{- end }}
{{- end }}