{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csdp-add-cluster.serviceAccountName" . }}
  namespace: {{ .Values.systemNamespace | default "kube-system" }}
  labels:
    {{- include "csdp-add-cluster.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
