apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: workflow-reporter
spec:
  eventBusName: codefresh-eventbus
  resource:
    workflows:
      eventTypes:
        - ADD
        - UPDATE
        - DELETE
      filter:
        createdBy: null
      namespace: REPLACE_ME
      group: argoproj.io
      resource: workflows
      version: v1alpha1
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: cf
    container:
      name: ""
      resources: {}
    serviceAccountName: codefresh-sa
