{{- if .Values.csdpInstaller.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: csdp-installer
  labels:
    {{- include "csdp-installer.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: {{ .Values.csdpInstaller.installer.ttlSecondsAfterFinished }}
  backoffLimit: {{ .Values.csdpInstaller.installer.backoffLimit }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        {{- include "csdp-installer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ .Values.csdpInstaller.installer.serviceAccount }}
      restartPolicy: Never
      containers:
        - name: csdp-installer
          image: "{{ .Values.csdpInstaller.installer.image.repository }}:{{ .Values.csdpInstaller.installer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.csdpInstaller.installer.image.pullPolicy }}
          command:
            - bash
          args:
            - ./install.sh
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CSDP_URL
              value: {{ .Values.csdpInstaller.platform.url | quote }}
            - name: CSDP_TOKEN
              valueFrom:
                secretKeyRef:
{{ .Values.csdpInstaller.platform.token.secretKeyRef | toYaml | indent 18 }}
            - name: CSDP_RUNTIME_NAME
              value: {{ .Values.csdpInstaller.runtime.name | quote }}
            - name: CSDP_RUNTIME_REPO
              value: {{ .Values.csdpInstaller.runtime.repoURL }}
            {{- if .Values.csdpInstaller.runtime.repoPath }}
            - name: CSDP_RUNTIME_REPO_PATH
              value: {{ .Values.csdpInstaller.runtime.repoPath }}
            {{- end }}
            - name: CSDP_RUNTIME_GIT_TOKEN
              valueFrom:
                secretKeyRef:
{{ .Values.csdpInstaller.runtime.gitToken.secretKeyRef | toYaml | indent 18 }}
            - name: CSDP_RUNTIME_CLUSTER
              value: {{ .Values.csdpInstaller.runtime.cluster | quote }}
            - name: CSDP_RUNTIME_INGRESS_URL
              value: {{ .Values.csdpInstaller.runtime.ingressURL | quote }}
            - name: CSDP_INGRESS_CLASS_NAME
              value: {{ .Values.csdpInstaller.runtime.ingressClass | quote }}
            - name: CSDP_INGRESS_CONTROLLER
              value: {{ .Values.csdpInstaller.runtime.ingressController | quote }}
            - name: CSDP_MANAGED_RUNTIME
              value: {{ .Values.csdpInstaller.runtime.managed | quote }}
            {{- if .Values.csdpInstaller.runtime.gitIntegration }}
            {{- if eq .Values.csdpInstaller.runtime.managed true }}
            {{ fail "git integration parameters are not allowed when 'runtime.managed' is true!"}}
            {{- end }}
            - name: CSDP_GIT_INTEGRATION_PROVIDER
              value: {{ .Values.csdpInstaller.runtime.gitIntegration.provider }}
            - name: CSDP_GIT_INTEGRATION_API_URL
              value: {{ .Values.csdpInstaller.runtime.gitIntegration.apiURL }}
            {{- if .Values.csdpInstaller.runtime.gitIntegration.token }}
            - name: CSDP_GIT_INTEGRATION_TOKEN
              valueFrom:
                secretKeyRef:
{{ .Values.csdpInstaller.runtime.gitIntegration.token.secretKeyRef | toYaml | indent 18 }}
            {{- end}}
            {{- end}}
          resources:
            {{- toYaml .Values.csdpInstaller.installer.resources | nindent 12 }}
{{ end }}
