{{- if .Values.csdpInstaller.enabled }}
{{- if .Values.csdpInstaller.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: csdp-installer
  labels:
    {{- include "csdp-installer.labels" . | nindent 4 }}
stringData:
    platformToken: {{ .Values.csdpInstaller.secrets.platform.token }}
    runtimeGitToken: {{ .Values.csdpInstaller.secrets.runtime.gitToken }}
{{- end }}
{{- end }}