apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../components/codefresh-base
patches:
# Set 2 replicas for workflow controller
- target:
    group: apps
    version:  v1
    kind: Deployment
    name: workflow-controller
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2