apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: codefresh-eventbus
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  jetstream:
    version: 2.8.1
    replicas: 3
    maxPayload: "2MB"
    streamConfig: |
      maxAge: 24h
      maxBytes: 200MB
    settings: |
      max_file_store: 1GB
      max_memory_store: 100MB
    startArgs:
      - "-D"                    # debug-level logs
    containerTemplate:
        resources:
          limits:
            cpu: 128m
            ephemeral-storage: 2Gi
          requests:
            cpu: 64m
            memory: 50Mi
            ephemeral-storage: 2Gi
