apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: codefresh-eventbus
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  nats:
    native:
      replicas: 3
      auth: token
      maxPayload: "2MB"
      containerTemplate:
        resources:
          limits:
            cpu: 128m
            ephemeral-storage: 2Gi
          requests:
            cpu: 64m
            memory: 50Mi
            ephemeral-storage: 2Gi
