apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Replace all variables with real values and run kustomize build on this file
resources:
  - https://github.com/codefresh-sandbox/csdp-official.git/kustomize?ref=<RUNTIME_VERSION>

namespace: csdp-runtime

secretGenerator:
  - name: csdp-installer
    behavior: merge
    literals:
      - "csdp.url=<CSDP_URL>"
      - "csdp.token=<CSDP_TOKEN>"
      - "runtime.name=<RUNTIME_NAME>"
      - "runtime.repo=<RUNTIME_REPO>"
      - "runtime.gitToken=<RUNTIME_GIT_TOKEN>"
      - "runtime.cluster=<RUNTIME_CLUSTER>"
      - "runtime.managed=<IS_MANAGED>"
      - "runtime.ingressURL=<RUNTIME_INGRESS_URL>"
      - "runtime.ingressClass=<RUNTIME_INGRESS_CLASS>"
      - "runtime.ingressController=<RUNTIME_INGRESS_CONTROLLER>"
