apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cap-app-proxy
spec:
  ingressClassName: REPLACE_ME
  rules:
  - host: REPLACE_ME
    http:
      paths:
      - backend:
          service:
            name: cap-app-proxy
            port:
              number: 3017
        path: /app-proxy
        pathType: Prefix
