apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - pdb.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: EventSource
      name: events-reporter
    patch: |-
      - op: add
        path: /spec/replicas
        value: 2
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Sensor
      name: events-reporter
    patch: |-
      - op: add
        path: /spec/replicas
        value: 2
