apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - default-rbac.yaml

images:
  - name: quay.io/codefresh/argocd
    newTag: v2.4.15-cap-CR-15028-last-changes
  - name: quay.io/codefresh/applicationset
    newTag: v0.4.2-CR-13254-remove-private-logs

configMapGenerator:
  - behavior: merge
    name: argocd-cm
    literals:
      - timeout.reconciliation=20s
      - accounts.admin=apiKey,login
  - behavior: merge
    name: argocd-cmd-params-cm
    literals:
      - server.insecure=true

# reset the crbs to `subject.namespace: default`, so that argo-cd will later change them to the actual ns
patches:
  - target:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      version: v1
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: default
  - target:
      version: v1
      kind: Service
      name: argocd-server
    patch: |
      - op: add
        path: /spec/ports/0/appProtocol
        value: grpc
      - op: add
        path: /spec/ports/1/appProtocol
        value: grpc

  - target:
      name: argocd-repo-server
      kind: Deployment
      group: apps
      version: v1
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: 256Mi
            ephemeral-storage: 2Gi
          limits:
            ephemeral-storage: 4Gi

  - target:
      name: argocd-application-controller
      kind: StatefulSet
      group: apps
      version: v1
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: 256Mi
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ARGOCD_CLUSTER_CACHE_LIST_SEMAPHORE
          value: "5"

  - target:
      name: argocd-applicationset-controller
      kind: Deployment
      group: apps
      version: v1
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: 256Mi
            ephemeral-storage: 1Gi
          limits:
            ephemeral-storage: 2Gi
