apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - default-rbac.yaml

images:
  - name: quay.io/codefresh/argocd
    newTag: v2.6.0-cap-CR-17237
  - name: quay.io/codefresh/applicationset
    newTag: v0.4.2-CR-13254-remove-private-logs

configMapGenerator:
  - behavior: merge
    name: argocd-cm
    literals:
      - timeout.reconciliation=20s
      - accounts.admin=apiKey,login
  - behavior: merge
    name: argocd-cmd-params-cm
    literals:
      - server.insecure=true

# reset the crbs to `subject.namespace: default`, so that argo-cd will later change them to the actual ns
patches:
  - target:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      version: v1
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: default

  # Istio protocol selection: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/
  # Ovveride the default protocol selection which is done by the port name (http), since this port is being used for both http and grpc.
  - target:
      version: v1
      kind: Service
      name: argocd-server
    patch: |
      - op: add
        path: /spec/ports/0/appProtocol
        value: tcp

  - target:
      name: argocd-repo-server
      kind: Deployment
      group: apps
      version: v1
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            ephemeral-storage: 2Gi
          limits:
            ephemeral-storage: 4Gi

  - target:
      name: argocd-application-controller
      kind: Deployment
      group: apps
      version: v1
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: 300Mi

  - target:
      name: argocd-applicationset-controller
      kind: Deployment
      group: apps
      version: v1
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: 300Mi
            ephemeral-storage: 1Gi
          limits:
            ephemeral-storage: 2Gi
