apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  creationTimestamp: null
  name: csdp
  namespace: default # replace
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: csdp project
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: csdp
  namespace: default # replace
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - git:
        repoURL: https://github.com/codefresh-io/csdp-official-poc.git
        revision: RUNTIME_VERSION
        directories:
          - path: csdp/hybrid/*
        requeueAfterSeconds: 15
        template:
          metadata:
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            destination: {}
            project: ""
            source:
              repoURL: ""
    - git:
        repoURL: https://github.com/codefresh-io/csdp-official-poc.git
        revision: RUNTIME_VERSION
        directories:
          - path: csdp/hybrid/argo-cd
        requeueAfterSeconds: 15
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
            source:
              repoURL: ""
    - git:
        files:
          - path: csdp/hybrid/**/config_dir.json
        repoURL: https://github.com/codefresh-io/csdp-official-poc.git
        requeueAfterSeconds: 15
        revision: RUNTIME_VERSION
        template:
          metadata:
            labels:
              codefresh.io/entity: "{{labels.codefresh_io_entity}}"
              codefresh.io/internal: "{{labels.codefresh_io_internal}}"
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            destination: {}
            project: ""
            source:
              repoURL: "{{srcRepoURL}}"
              path: "{{srcPath}}"
              targetRevision: "{{srcTargetRevision}}"
              directory:
                exclude: "{{exclude}}"
                include: "{{include}}"
                recurse: true
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{path.basenameNormalized}}"
        codefresh.io/entity: "component"
        codefresh.io/internal: "true"
      name: csdp-{{path.basenameNormalized}}
      namespace: default # replace
    spec:
      destination:
        namespace: default # replace
        server: "https://kubernetes.default.svc"
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
      project: csdp
      source:
        path: csdp/hybrid/{{path.basenameNormalized}}
        repoURL: https://github.com/codefresh-io/csdp-official-poc.git
        targetRevision: RUNTIME_VERSION # replace with runtime version
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
