apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../../_components/codefresh-base
  - ../../_components/ha-manifests

# remove once app-proxy is merged
images:
  - name: quay.io/codefresh/cap-app-proxy
    newTag: 1.1689.0-CR-13336-app-proxy-ha-3fe8fb7
