apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../_components/apps/argo-workflows/_bundles/basic/

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  # Holds the weight for workflow semaphores to configure their concurrency.
  # We restrict concurrency only for managed runtimes.
  - name: workflow-synchronization-semaphores
    behavior: create
    literals:
      - imageReportExecutor=2