apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/argo-workflows

configMapGenerator:
  # Holds the weight for workflow semaphores to configure their concurrency.
  # We restrict concurrency only for managed runtimes.
  - name: workflow-synchronization-semaphores
    behavior: create
    literals:
      - imageReportExecutor=2