apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/argo-workflows

configMapGenerator:
  - name: workflow-synchronization-semaphores
    behavior: create
    literals:
      - imageReportExecutor=2