on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  kube-score:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubescore
        uses: tobbbles/setup-kubescore@v1.0.3
      - name: test
        run: ls
      - name: kube-score check
        run: 'kube-score score ./csdp/**/*.yaml'
