on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 
jobs:
  kube-score:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: kube-score check
        uses: piraces/kube-score-ga@v0.1.3
        with:
          manifests-folders: 'csdp/**/*.yaml,csdp/**/*.yml'
