on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  kube-score:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubescore
        uses: tobbbles/setup-kubescore@v1.0.3
      - name: test
        run: ls
      - name: kube-score check
        run: find . -name '*.yaml' \
                -type f \
                -not -name './**/README.yaml' \
                -not -path '*/helm/*' \
                -not -name 'kustomization.yaml' \
                -not -name '*.patch.yaml' \
                -print \
                -exec kube-score score {} -o ci \
                  --ignore-test container-security-context-privileged \
                  --ignore-test pod-networkpolicy \
                  --ignore-test container-security-context-user-group-id \
                  --ignore-test container-image-tag \
                  --ignore-test container-ephemeral-storage-request-and-limit \
                  --ignore-test container-security-context-readonlyrootfilesystem \;
